#!/usr/bin/env python3
"""Point the derived run's evidence declarations at the frozen/derived artifacts.

The derived run is a relocated copy of the original run directory, so the
operator-relative `../operator/fixture/...` paths no longer resolve. This script
keeps the original declarations' hashes but makes the paths absolute, points the
test-mod declaration at the fixed projection, and records the derivation in
run.json. It never edits the original run or the freeze snapshot.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path("F:/mc-agent-worktrees/rom13/coldstart/labs/rom20-20260926T063100Z")
DERIVED = ROOT / "operator" / "post-task-derived"
FREEZE = ROOT / "operator" / "post-task-freeze"
RUN = DERIVED / "run"
LIVE_OPERATOR = ROOT / "operator"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    evidence_path = RUN / "evidence.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))

    # abs paths for the operator-side files (they are not part of the agent freeze)
    fixture = LIVE_OPERATOR / "fixture" / "ready-snapshot.json"
    preflight = LIVE_OPERATOR / "preflight" / "preflight.json"
    assert fixture.is_file() and preflight.is_file(), "operator fixture/preflight missing"
    for name, path, declared in (
        ("fixture", fixture, "5318883757397db34f376011bcfb88e00bcf9ea919321b86079b2d48fb0348f9"),
        ("preflight", preflight, "2f786e24056029910866f4ccb3c21b84195bab4a12beb7cb23b56f68fafe942e"),
    ):
        actual = sha256(path)
        assert actual == declared, f"{name} hash changed: {actual}"
        evidence[name] = {"path": str(path), "sha256": actual}

    outputs = {
        name: DERIVED / "evidence" / name
        for name in ("answer.json", "oracle.json", "romlog.experiment.norm.jsonl", "testmod.experiment.jsonl", "restore-evidence.json")
    }
    for path in outputs.values():
        assert path.is_file(), f"missing derived evidence: {path}"

    raw_logger = FREEZE / "agent-logger-raw" / "romlog.jsonl"
    raw_audit = FREEZE / "testmod" / "audit-rom20-20260926T063100Z.jsonl"
    evidence["agent_logger"] = {
        "path": str(raw_logger.resolve()),
        "sha256": sha256(raw_logger),
        "normalized": str(outputs["romlog.experiment.norm.jsonl"].resolve()),
        "normalized_sha256": sha256(outputs["romlog.experiment.norm.jsonl"]),
        "note": "raw logger copied into the post-task freeze; normalized view regenerated by the fixed make_evidence",
    }
    evidence["test_mod"] = {
        "path": str(outputs["testmod.experiment.jsonl"].resolve()),
        "sha256": sha256(outputs["testmod.experiment.jsonl"]),
        "raw": str(raw_audit.resolve()),
        "raw_sha256": sha256(raw_audit),
        "note": "fixed canonical projection (raw session order, input_request included); raw audit preserved in the freeze",
    }
    evidence["answer"] = {"path": str(outputs["answer.json"].resolve()), "sha256": sha256(outputs["answer.json"])}
    evidence["oracle"] = {"path": str(outputs["oracle.json"].resolve()), "sha256": sha256(outputs["oracle.json"])}
    evidence["restore"] = {
        "path": str(outputs["restore-evidence.json"].resolve()),
        "sha256": sha256(outputs["restore-evidence.json"]),
    }
    evidence["derivation_note"] = (
        "derived run: fixture/preflight paths made absolute for relocation; test_mod points at the fixed "
        "projection; agent logger raw output is the frozen copy. Raw task evidence remains the freeze snapshot."
    )
    evidence_path.write_text(json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    run_path = RUN / "run.json"
    run = json.loads(run_path.read_text(encoding="utf-8"))
    derivation = json.loads((RUN / "trajectory-derivation.json").read_text(encoding="utf-8"))
    run["trajectory_derivation"] = {
        "raw_session": derivation["sources"]["raw_session"],
        "original_trajectory": derivation["sources"]["original_trajectory"],
        "canonical": derivation["outputs"],
        "merge": derivation["merge"],
        "derivation_file": "trajectory-derivation.json",
        "created_at_preserved": run.get("created_at"),
    }
    run_path.write_text(json.dumps(run, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({k: evidence[k].get("path") if isinstance(evidence[k], dict) else evidence[k] for k in ("agent_logger", "test_mod", "answer", "oracle", "restore")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
